name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@b6b33c4
      with: {version: '1.39.14'}
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.emscripten_cache
        key: emscripten-1.39.14
    - name: make
      run: make
    - uses: actions/upload-artifact@master
      with: {name: dist, path: dist}
    - name: test
      run: npm ci && npm test
