name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mymindstorm/setup-emsdk@v1
      with:
        version: '1.38.47'
    - name: install coffee
      run: npm install --global coffeescript@1
    - name: make
      run: make
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: test
      run: npm ci && npm test
