name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mymindstorm/setup-emsdk@v1
      with:
        version: '1.38.48'
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.emscripten_cache
        key: emscripten-1.38.48
    - name: make
      run: make
    - name: test
      run: npm ci && npm test
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist
